[application]
name = "obin"
version = "0.3.0"
entry = "src/main.dlt"
type = "console"

[build]
default-target = "windows"
default-profile = "release"
incremental = true
targets = ["windows", "linux"]

[targets.windows]
triple = "windows/x86_64-msvc"

[targets.linux]
triple = "linux/x86_64-musl"

[profiles.dev]
optimization = 0
no-console = false

[profiles.release]
optimization = 3
no-console = false

[packages]
auto-sync = true

[package]
directory = "dist"
include-assets = false
