[application]
name = "obin"
version = "0.3.0"
entry = "src/main.dlt"
type = "console"

[build]
default-target = "windows"
default-profile = "release"
incremental = true

[targets.windows]
id = "windows/x86_64"

[targets.linux]
id = "linux/x86_64"

[profiles.dev]
optimization = 0
no-console = false

[profiles.release]
optimization = 3
no-console = false

[packages]
auto-sync = true

[package]
directory = "dist"
include-assets = false
